### ISSUE TITLE
Contributions / collaboration

### ISSUE THREAD

**Issue by pgl** [mallory/DNS-Privacy#16]
How would someone contribute or collaborate on updates to the document?

Just submit a PR with their proposed updates? Or is there a group or something to join?

**Comment by ShivanKaul** [comment]
@pgl PRs are very welcome! Thanks for your earlier one. @mallory and I are planning to push some changes to address some issues you and others raised. Issues are also a good place IMO to discuss and plan. If you have some larger thoughts, we could perhaps do a call. We don't have a group or anything just yet.

**Comment by pgl** [comment]
@ShivanKaul OK, thanks. It felt like perhaps there was something I was missing - I guess the planning you mentioned just now. But if PRs are the way to go then thanks for the information.
