### ISSUE TITLE
Best practices and common policies

### ISSUE THREAD

**Issue by pgl** [mallory/DNS-Privacy#9]
Two documents that may be worth referencing:

 * RFC 8932 - Recommendations for DNS Privacy Service Operators (https://tools.ietf.org/html/rfc8932)
 * European Resolver Policy (https://europeanresolverpolicy.com/) - built on RFC 8932

**Comment by mallory** [comment]
Thanks! We do already reference RFC 8932, but the ERP doesn't fully align with the aims of the paper so we won't reference it. Hopefully other works related to ERP would reference this paper though.
